# -*- coding: utf-8 -*-
"""jpg_cv2_gaussianfilter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N45FKpwht4J1g3YEEkZATkCuG8Qk_xpQ
"""

!git clone https://github.com/kecosz/cv2_jpg_preprocessing.git

import numpy as np
import matplotlib.pyplot as plt
#from keras.preprocessing import image
#from keras.preprocessing.image import ImageDataGenerator,array_to_img,img_to_array
import cv2
from google.colab.patches import cv2_imshow

import glob
files = glob.glob("cv2_jpg_preprocessing/data/jpg111523/*") #set sample file folder
files

im_gauss_s = []
for n,i in enumerate(files):
  im = cv2.imread(i)
  im_gauss = cv2.GaussianBlur(im, (5, 5), 50) #set parameters
  imgs = cv2.hconcat([im, im_gauss])
  cv2_imshow(imgs)
  im_gauss_s.append(im_gauss)

